# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wallet.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'wallet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\x12\x05proto\";\n\x0e\x43SGetWalletReq\x12\x13\n\x0blogin_token\x18\x01 \x01(\t\x12\x14\n\x0ctopup_rebate\x18\x02 \x01(\x08\"l\n\rAccountWallet\x12\r\n\x05\x63oins\x18\x01 \x01(\r\x12\x0c\n\x04gems\x18\x02 \x01(\x05\x12\x10\n\x08gop_gems\x18\x03 \x01(\r\x12\x13\n\x0btotal_topup\x18\x04 \x01(\x04\x12\x17\n\x0flast_topup_time\x18\x05 \x01(\x03\"^\n\x0e\x43SGetWalletRes\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12$\n\x06wallet\x18\x02 \x01(\x0b\x32\x14.proto.AccountWallet\x12\x12\n\npaid_level\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETWALLETREQ']._serialized_start=23
  _globals['_CSGETWALLETREQ']._serialized_end=82
  _globals['_ACCOUNTWALLET']._serialized_start=84
  _globals['_ACCOUNTWALLET']._serialized_end=192
  _globals['_CSGETWALLETRES']._serialized_start=194
  _globals['_CSGETWALLETRES']._serialized_end=288
# @@protoc_insertion_point(module_scope)
